// with-remix/app/components/ProductCard.tsx
import { Link } from 'react-router'

type ProductCardProps = {
  id: string
  name: string
  description?: string | null
  image?: string | null
  priceAmount?: number
  priceCurrency?: string
}

export function ProductCard(props: ProductCardProps) {
  const formattedPrice = props.priceAmount
    ? new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: props.priceCurrency || 'USD',
    }).format(props.priceAmount / 100)
    : '—'

  const checkoutHref = `/polar/checkout?products=${encodeURIComponent(props.id)}`

  return (
    <div className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 overflow-hidden rounded-lg hover:shadow-lg transition-shadow">
      <img src={props.image || '/placeholder.svg'} alt={props.name} className="w-full h-48 object-cover" />
      <div className="p-6">
        <h3 className="text-xl font-semibold mb-2">{props.name}</h3>
        <p className="text-gray-600 dark:text-gray-400 mb-4">{props.description}</p>
        <div className="flex items-center justify-between">
          <span className="text-2xl font-medium">{formattedPrice}</span>
          <Link to={checkoutHref} className="px-4 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors">
            Buy Now
          </Link>
        </div>
      </div>
    </div>
  )
}

// with-nuxt/app/components/ProductCard.vue
<template>
  <div class="bg-card border border-border overflow-hidden hover:shadow-lg transition-shadow">
    <NuxtImg :src="image || '/placeholder.svg'" :alt="name" class="w-full h-48 object-cover" />
    <div class="p-6">
      <h3 class="text-xl font-heading font-semibold text-card-foreground mb-2">
        {{ name }}
      </h3>
      <p class="text-muted-foreground mb-4">{{ description }}</p>
      <div class="flex items-center justify-between">
        <span class="text-2xl font-medium text-primary">{{ formattedPrice }}</span>
        <button @click="buyNow" class="px-4 py-2 bg-gray-200 text-primary-foreground font-medium rounded-lg hover:bg-primary/90 transition-colors cursor-pointer">Buy Now</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  id: string
  name: string
  description?: string | null
  image?: string | null
  priceAmount?: number
  priceCurrency?: string
}>()

const formattedPrice = computed(() =>
  props.priceAmount
    ? new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: props.priceCurrency || 'USD',
      }).format(props.priceAmount / 100)
    : '—',
)

const buyNow = () => {
  const customerId = sessionStorage.getItem('customerId')
  const customerEmail = sessionStorage.getItem('customerEmail')
  const customerName = sessionStorage.getItem('customerName')
  const url = new URL('/api/checkout', window.location.origin)

  url.searchParams.append('products', props.id)
  if (customerId) {
    url.searchParams.append('customerId', customerId)
  }
  if (customerEmail) {
    url.searchParams.append('customerEmail', customerEmail)
  }
  if (customerName) {
    url.searchParams.append('customerName', customerName)
  }
  window.location.href = url.toString()
}
</script>
